name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Trigger the action when pushing to the main branch
  pull_request:
    branches:
      - master  # Trigger the action on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu GitHub-hosted runner

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (optional, but recommended for modern Docker builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub (you need to store Docker Hub credentials as GitHub secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image using the Dockerfile
    - name: Build Docker image
      run: |
        docker build -t amanharsora543211/project:${{ github.sha }} .

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push amanharsora543211/project:${{ github.sha }}

    # Step 6: Run the Docker container (use any ports and settings required by your application)
    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 amanharsora543211/project:${{ github.sha }}

